on:
  pull_request:
  push:
    branches:
    - main
    - master
  schedule:
    - cron: '0 15 * * 0'
  workflow_dispatch:
name: Checkmarx SAST Scan
jobs:
  call-reusable-checkmarx:
    name: Call Reusable Checkmarx Workflow
    uses: Replicon/time-intelligence-web/.github/workflows/reusable-checkmarx.yml@main
    with:
      timeout_minutes: 90
      scheduled_timeout_minutes: 360
    secrets:
      checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }}
      checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
      checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}

